version: '3.4'

networks:
  backend:
  frontend:

services:
  spadb:
    container_name: spa-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 8002:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=StrongP@ssw0rd!
    networks:
      - backend
  spa-app-comments:
    container_name: spa-app-comments
    image: ${DOCKER_REGISTRY-}spaappcomments
    build:
      context: .
      dockerfile: SPA-app-comments/Dockerfile
    ports:
      - 8001:80
    depends_on:
      - spadb
    networks:
      - backend